name: leetcode
on:
  push:
    branches:
      - master
      - develop
      - feature/**
      - ci/**
  pull_request:
    branches:
      - master
      - develop
      - feature/**
      - ci/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 21
      - name: Setup Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GH_TOKEN }}
      - name: Unit Tests
        run: task test
      - name: Code Coverage
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: false
