name: Makefile CI
on:
  push:
    branches:
      - master
      - develop
      - feature/**
      - ci/**
  pull_request:
    branches:
      - master
      - develop
      - feature/**
      - ci/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: "20.0.1"
          distribution: "temurin"
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Unit Tests
        run: ./gradlew test
